name: my_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  te_widgets:
    path: ../../packages/te_widgets
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.5.3
  go_router: ^15.1.2

  dio: ^5.8.0+1
  pretty_dio_logger: ^1.3.1
  dart_mappable: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
